### This workflow setup instance then build and push images ###
name: Multi-arch build

run-name: >-
  Build Monday: 
  VER: [${{ inputs.tag }}]
  REPO: [${{ inputs.repo }}]

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Specify tag (ex. 1.0.0 or 1.0.0-rc25)'
        type: string
        required: true
      repo:
        description: Mode
        required: true
        default: testing
        type: choice
        options:
        - test
        - production
    
jobs:
  build:
    name: "Build monday"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
        with:
          ref: 'develop'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      #- name: Login to Container Registry
      #  uses: docker/login-action@v3
      #  with:
      #    registry: ${{ (inputs.repo == 'test') && secrets.DOCKER_TEST_REGISTRY || 'docker.io' }}
      #    username: ${{ (inputs.repo == 'test') && secrets.DOCKER_TEST_USERNAME || secrets.DOCKER_HUB_USERNAME }}
      #    password: ${{ (inputs.repo == 'test') && secrets.DOCKER_TEST_ACCESS_TOKEN || secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build
        run: |
          ./mvnw package -pl onlyoffice-monday-gateway -am
          ./mvnw package -pl onlyoffice-monday-tenant -am
          ./mvnw package -pl onlyoffice-monday-user -am
          ./mvnw -pl onlyoffice-monday-gateway jib:dockerBuild -Ddocker.image.name=docker.onlyoffice.com/monday-gateway:1.0.0-rc15
          ./mvnw -pl onlyoffice-monday-tenant jib:dockerBuild -Ddocker.image.name=docker.onlyoffice.com/monday-tenant:1.0.0-rc15
          ./mvnw -pl onlyoffice-monday-user jib:dockerBuild -Ddocker.image.name=docker.onlyoffice.com/monday-user:1.0.0-rc15
          echo "PUSH IMAGE"
          #docker push docker.onlyoffice.com/monday-gateway:1.0.0-rc15
          #docker push docker.onlyoffice.com/monday-tenant:1.0.0-rc15
          #docker push docker.onlyoffice.com/monday-user:1.0.0-rc15
