### This workflow setup instance then build and push images ###
name: Multi-arch build

run-name: >-
  Build Monday: 
  VER: [${{ inputs.tag }}]
  REPO: [${{ inputs.repo }}]

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Specify tag (ex. 1.0.0 or 1.0.0-rc25)'
        type: string
        required: true
      repo:
        description: Mode
        required: true
        default: testing
        type: choice
        options:
        - test
        - production
    
jobs:
  build:
    name: "Build monday"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          #registry: ${{ inputs.repo == 'test' && secrets.DOCKER_TEST_REGISTRY || 'docker.io' }}
          registry: ${{ (inputs.repo == 'test') && 'test' || 'docker.io' }}
          username: ${{ (inputs.repo == 'test') && secrets.DOCKER_TEST_USERNAME || secrets.DOCKER_HUB_USERNAME }}
          password: ${{ (inputs.repo == 'test') && secrets.DOCKER_TEST_ACCESS_TOKEN || secrets.DOCKER_HUB_ACCESS_TOKEN }}
